# Generated by Django 5.1.6 on 2026-03-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('committee_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('chamber', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('congress_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CongressMember',
            fields=[
                ('bio_guide_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=255)),
                ('inverse_name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.committee')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.sector')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='sector',
            field=models.ManyToManyField(through='server.CommitteeSector', to='server.sector'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(default=models.CharField(max_length=9, primary_key=True, serialize=False), max_length=255)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], max_length=1)),
                ('party', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.congress')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.congressmember')),
            ],
            options={
                'unique_together': {('member', 'congress', 'chamber')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.committee')),
                ('member_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.term')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_members',
            field=models.ManyToManyField(through='server.CommitteeMembership', to='server.term'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell'), ('E', 'Exchange')], max_length=1)),
                ('date', models.DateField()),
                ('disclosure_date', models.DateField(default='9999-01-01')),
                ('amount', models.IntegerField()),
                ('conflicted', models.BooleanField(default=False)),
                ('price_at_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.ForeignKey(db_column='bio_guide_id', on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='server.congressmember')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.stock')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False)),
                ('buy_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_as_buy', to='server.trade')),
                ('sell_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments_as_sell', to='server.trade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('buy_trade',), name='unique_buy_trade_segment')],
            },
        ),
    ]
