# Generated by Django 5.1.6 on 2026-04-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ret', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('retx', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('vwretd', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('sprtrn', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='server.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='server_stoc_ticker_c99c16_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
