# Generated by Django 5.1.6 on 2026-04-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
