# Generated by Django 5.1.6 on 2026-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_trade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
