# Generated by Django 5.1.6 on 2026-01-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_tradesegment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.sector'),
        ),
    ]
