# Generated by Django 5.1.6 on 2026-05-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_stock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('jacket_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chamber', models.CharField(max_length=1)),
                ('title', models.TextField(null=True)),
                ('transcript', models.TextField(null=True)),
                ('committees', models.ManyToManyField(related_name='hearings', to='server.committee')),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.congress')),
            ],
        ),
    ]
