# Generated by Django 5.1.6 on 2026-05-21 15:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_hearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
