# Generated by Django 5.1.6 on 2026-05-22 21:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_hearing_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
