# Generated by Django 5.1.6 on 2026-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_congressmember_inverse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressmember',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
