# Generated by Django 5.1.6 on 2026-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_term_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='id',
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_code',
            field=models.CharField(default='placeholder', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
