# Generated by Django 5.1.6 on 2026-03-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_remove_stock_new_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='disclosure_date',
            field=models.DateField(default='9999-01-01'),
        ),
    ]
