# Generated by Django 5.1.6 on 2026-03-24 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_trade_disclosure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='committeesector',
            name='sector',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='server.sector'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='committee',
            name='sector',
        ),
        migrations.CreateModel(
            name='Subcommittee',
            fields=[
                ('subcommittee_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subcommittee_name', models.CharField(max_length=255)),
                ('chamber', models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], max_length=1)),
                ('parent_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcommittees', to='server.committee')),
            ],
        ),
        migrations.CreateModel(
            name='SubcommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('member_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.term')),
                ('subcommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.subcommittee')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='sector',
            field=models.ManyToManyField(through='server.CommitteeSector', to='server.sector'),
        ),
    ]
