# Generated by Django 5.1.6 on 2026-03-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_committee_type_committeesector_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcommitteemembership',
            name='subcommittee',
        ),
        migrations.RemoveField(
            model_name='subcommitteemembership',
            name='member_term',
        ),
        migrations.AddField(
            model_name='committee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcommittees', to='server.committee'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Subcommittee',
        ),
        migrations.DeleteModel(
            name='SubcommitteeMembership',
        ),
    ]
