# Generated by Django 5.1.6 on 2026-03-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_remove_subcommitteemembership_subcommittee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chamber',
            field=models.CharField(max_length=1),
        ),
    ]
