# Generated by Django 5.1.6 on 2026-03-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_alter_committee_chamber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='parent',
        ),
    ]
