# Generated by Django 5.1.6 on 2026-03-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_remove_committee_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='checked',
            new_name='conflicted',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='updated_at',
        ),
    ]
