# Generated by Django 5.1.6 on 2025-12-10 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSegment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('buy_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trade', to='server.trade')),
                ('sell_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trade', to='server.trade')),
            ],
        ),
    ]
