# Generated by Django 5.1.6 on 2025-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_tradesegment_buy_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesegment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
