# Generated by Django 5.1.6 on 2026-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_stock_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemembership',
            name='congress_number',
            field=models.IntegerField(default=119),
        ),
    ]
