# Generated by Django 5.1.6 on 2026-03-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_committeemembership_congress_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('congress_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='congress_number',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='congressmember',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='congressmember',
            name='party',
        ),
        migrations.RemoveField(
            model_name='congressmember',
            name='state',
        ),
        migrations.RemoveField(
            model_name='congressmember',
            name='term',
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], max_length=1)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.congress')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.congressmember')),
            ],
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='member_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.term'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_members',
            field=models.ManyToManyField(through='server.CommitteeMembership', to='server.term'),
        ),
    ]
