# Generated by Django 5.1.6 on 2026-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_congressmember_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='party',
            field=models.CharField(max_length=2),
        ),
    ]
