# Generated by Django 5.1.6 on 2026-03-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_term_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('member', 'congress')},
        ),
    ]
