# Generated by Django 5.1.6 on 2026-03-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_committee_id_committee_committee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='traded_by',
        ),
    ]
