# Generated by Django 5.1.6 on 2026-03-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_remove_trade_traded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='current_price',
        ),
    ]
