# Generated by Django 5.1.6 on 2026-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell'), ('E', 'Exchange')], max_length=1),
        ),
    ]
