# Generated by Django 5.1.6 on 2026-03-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_trade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='new_ticker',
        ),
    ]
